config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :categories
    resources :preferences
  end

  resources :brands
  resources :items

  root 'home#show'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :items
  has_and_belongs_to_many :preferences

  validates :name, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :preferences,  dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :preferences
  belongs_to :brand

  validates :name, presence: true
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :item
  belongs_to :brand
  has_attached_file :preference_image, styles: {
    thumb: '250x100#',
    square: '200x200#',
    medium: '300x300>'
  }
  validates_attachment_content_type :preference_image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :create_uncategorized

  has_many :preferences

  has_many :categories

  accepts_nested_attributes_for :preferences
  accepts_nested_attributes_for :categories

  def create_uncategorized
    self.categories.create!(name: "Uncategorized")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new( brand_params )
    if @brand.save
      redirect_to new_item_path
    else
      render :new
    end
  end
  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    @Brand.update(brand_params)

    if @brand.save
      flash[:notice] = "Your brand name was succesfully updated"
      redirect_to :back
    else
      render :edit
    end
  end
  private

  def brand_params
      params.require(:brand).permit([:name])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
     @categories = Category.order(name: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new( category_params )

    if @category.save
      flash[:success] = 'New category created.'
      redirect_to root_path
    else
      render :new
    end

  end

  def edit
    @category = Category.find(params[:id])
  end

  def show
    @category = Category.find(params[:id])
    @preferences = Preference.where(category_id: @category.id)
  end

  def update
    @category = current_user.category.assign_attributes(category_params)

    if @category.save
      flash[:success] = 'Category updated.'
      redirect_to :back
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy!
    flash[:success] = 'Category deleted.'
    redirect_to user_categories_path
  end

  private

  def category_params
      params.require(:category).permit([:name, :id])
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/documents_controller.rb
def create
  @document = current_user.documents.create(params[:document])
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @categories = Category.order(name: :desc).limit(18)
    @preferences = Preference.order(score: :desc).limit(18)

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new( item_params )
    if @item.save
      redirect_to new_user_preference_path(current_user)
    else
      render :new
    end
  end
  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @Item.update(item_params)

    if @item.save
      flash[:notice] = "Your item name was succesfully updated"
      redirect_to :back
    else
      render :edit
    end
  end
  private

  def item_params
      params.require(:item).permit([:name])
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

  def index
     @preferences = Preference.order(score: :desc)

  end

  def show
    @preference = Preference.find(params[:id])

  end

  def new
    @preference = Preference.new
  end

  def create
    @category = Category.find(params[:preference][:category])
    @item = Item.find(params[:preference][:item])

    @preference = current_user.preferences.new(preference_params)
    @preference.category = @category
    @preference.item = @item
    @item.brand = @brand

    if @preference.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @preference = Preference.find(params[:id])
  end

  def update
    @preference = Preference.find(params[:id])
    @preference.update(preference_params)

    if @preference.save
      flash[:notice] = "Your preference was succesfully updated"
      redirect_to user_preference_path(current_user, @preference.id)
    else
      render :edit
    end
  end

  def destroy
    @preference = Preference.find(params[:id])
    @preference.destroy!
    flash[:success] = 'Preference deleted.'
    redirect_to root_path
  end

  private

  def preference_params
    params.require(:preference).permit([:score, :comment, :preference_image, :category_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brands/new.html.erb
<div class="row">
  <div class="home-image"><%= image_tag("reco-home2.png") %></div>
</div>
<div class="row home-spacer">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <p class="tag-line">Add a new brand / type</p>
  </div>
  <div class="col-md-4"></div>
</div>

<div class="row">

  <div class="col-md-4"></div>

  <div class="col-md-3">
    <div class="home-spacer2"></div>
    <% if @brand.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <h4><strong><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</strong></h4>
        <ul><% @brand.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
    <% end %>

    <%= form_for @brand, :url => brands_path  do |f| %>
      <h1><%= f.text_field :name %></h1>
      <%= f.submit "Next", :class => "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-md-3 "></div>
</div>
<div class="home-spacer2"></div>
<div class="home-spacer2"></div>

app/views/categories/_category.html.erb
<% @categories.each do |category| %>
  <div class="category">
    <%= link_to category.name, user_category_path(current_user, category.id) %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="row">
  <div class="home-image"><%= image_tag("reco-home2.png") %></div>
</div>
<% category = current_user.categories.where(name: "uncategorized").first %>
<div class="row">

  <div class="col-sm-1 white-banner"></div>

  <div class="col-sm-6 white-banner">
    <h2>Current categories</h2>
  </div>

  <div class="col-sm-4 white-banner">
    <h4 class="button"> <%= link_to 'New category', new_user_category_path(current_user, Category.new) %>
    </h4>
    <h4 class="button"> <%= link_to 'New preference', new_user_preference_path(current_user, category, Preference.new) %>
    </h4>
  </div>

  <div class="col-sm-1 home-spacer"></div>
</div>
<div class="home-spacer2"></div>
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
  <%= render 'layouts/alerts' %>
    <% if user_signed_in? %>
      <% @categories.each do |category| %>
        <div class="category-large">
          <%= link_to category.name, user_category_path(current_user, category.id) %>
          <%= link_to user_category_path(current_user, category), method: :delete, data: { confirm: 'Delete this category?' } do %>
            <span class="glyphicon glyphicon-remove pull-right pencil"></span>
          <% end %>
        <%= link_to edit_user_category_path(current_user, category) do %>
          <span class="glyphicon glyphicon-pencil pull-right pencil"></span>
        <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-1"></div>


</div>


</div>
  <div class="col-md-3 "></div>
</div>
<div class="home-spacer2"></div>

app/views/categories/new.html.erb
<div class="row">
  <div class="home-image"><%= image_tag("reco-home2.png") %></div>
</div>
<div class="row home-spacer">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <p class="tag-line ">Create a new category</p>
  </div>
  <div class="col-md-3"></div>
</div>
<div class="row">
  <div class="col-md-3 "></div>

  <div class="col-md-6 ">
    <div class="home-spacer2"></div>
    <% if @category.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <h4><strong><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</strong></h4>
        <ul><% @category.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
    <% end %>

    <%= form_for @category, :url => user_categories_path  do |f| %>
      <h3><%= f.text_field :name %></h3>
      <div class="home-spacer2"></div>
      <%= f.submit "Create", :class => "btn btn-primary" %>
    <% end %>
    </div>
  <div class="col-md-3 "></div>
</div>
<div class="home-spacer2"></div>
<div class="home-spacer2"></div>
<div class="home-spacer2"></div>
<div class="home-spacer2"></div>

app/views/categories/show.html.erb
<div class="row">
  <div class="home-image"><%= image_tag("reco-home2.png") %></div>
</div>
<div class="row">

  <div class="col-md-6">
    <h2><%= @category.name.capitalize %></h2>
  </div>

  <div class="col-md-6">
    <h4 class="button pull-right"> <%= link_to 'New category', new_user_category_path(current_user, Category.new) %></h4>
    <h4 class="button pull-right"> <%= link_to 'New preference', new_brand_path %></h4>
    <h4 class="button pull-right"> <%= link_to 'View categories', user_categories_path(current_user) %></h4>
    <br>
  </div>

</div>
  <%= render 'preferences/preference' %>

app/views/home/show.html.erb
<!--Logged in user view -->
<% if user_signed_in? %>

<div class="row">
  <div class="home-image"><%= image_tag("reco-home2.png") %></div>
</div>

<div class="row">
  <div class="col-md-1 white-banner"></div>

  <div class="col-sm-12 col-md-5 white-banner">
    <h2>A few of my favorite things</h2>
  </div>

  <div class="col-sm-12 col-md-5 white-banner">
    <h4 class="button pull-right"> <%= link_to 'New category', new_user_category_path(current_user, Category.new) %></h4>
    <h4 class="button pull-right"> <%= link_to 'New preference', new_brand_path %></h4>
    <h4 class="button pull-right"> <%= link_to 'View categories', user_categories_path(current_user) %></h4>
    <br>
  </div>

  <div class="col-md-1 white-banner"></div>
</div>

<div class="row">
  <div class="col-md-1"></div>

  <div class="col-md-10">

  <%= render 'layouts/alerts' %>
      <%= @category = current_user.categories.where(name: "uncategorized").first %>
      <%= render 'categories/category' %>
  </div>

  <div class="col-md-1"></div>
</div>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <%= render 'preferences/preference' %>
  </div>
  <div class="col-md-1"></div>
</div>
<% end %>

<% if user_signed_in? == false %>
  <!--Introduction to the site -->
  <div class="row">
    <div class="home-image"><%= image_tag("reco-home.png") %></div>
  </div>

  <div class="row">
    <div class="home-spacer text-center">
      <p class="tag-line">Keep track of <i>everything</i> you like &mdash; and everything you don't.</p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div class="col-md-4 text-center symbols">
        <%= image_tag("camera.png", :class => "img-rounded") %><br>
        <br>
        <p class="lead">Upload images <br>of the products and <br>services you try.</p>
      </div>

      <div class="col-md-4 text-center symbols">
        <%= image_tag("grid.png", :class => "img-rounded") %><br>
        <br>
        <p class="lead">Group experiences into<br>custom categories. Track <br>what's important to you.</p>
      </div>

      <div class="col-md-4 text-center symbols">
        <%= image_tag("heart.png", :class => "img-rounded") %><br>
        <br>
        <p class="lead">Rate your experiences. <br>Recall the ones you love and <br>avoid the ones you don't.</p>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
<% end %>

<div class="home-spacer2"></div>

app/views/items/new.html.erb
<div class="row">
  <div class="home-image"><%= image_tag("reco-home2.png") %></div>
</div>
<div class="row home-spacer">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <p class="tag-line">Add a new item</p>
  </div>
  <div class="col-md-4"></div>
</div>

<div class="row">

  <div class="col-md-4"></div>

  <div class="col-md-3">
    <div class="home-spacer2"></div>
    <% if @item.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <h4><strong><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</strong></h4>
        <ul><% @item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
    <% end %>
    <%= form_for @item, :url => items_path  do |f| %>
     <h1> <%= f.text_field :name %></h1>
      <%= f.submit "Next", :class => "btn btn-primary"  %>
    <% end %>
    </div>
  <div class="col-md-3 "></div>
    <div class="col-md-2"></div>
</div>
<div class="row">
  <div class="home-spacer2"></div>
  <div class="home-spacer2"></div>
</div>

app/views/layouts/_alerts.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-success alert-dismissable" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
    <% if msg.is_a?(String) %>
      <%= content_tag :div, msg, :class => "flash_#{name}" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recollektion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>
<body>

<!-- Header and login -->
  <nav class="navbar-fixed-top" role="navigation">
  <div class="container-fluid accent">
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10">
        <span class="title"><%= link_to 'Recollektion', root_path %></span>
        <span class="navbar-right">
          <% if user_signed_in? %>
            <div class="login-nav">Logged in as <strong><%= current_user.email %></strong>
              <button type="button" class="btn btn-med" id="login"><%= link_to 'Edit profile', edit_user_registration_path %> </button>
              <button type="button" class="btn btn-med" id="login"><%= link_to "Logout", destroy_user_session_path, method: :delete %></button>
            </div>
          <% else %>
            <div class="login-nav">
              <button type="button" class="btn btn-med" id="login"><%= link_to "Sign up", new_user_registration_path %> </button>
              <button type="button" class="btn btn-med" id="login"><%= link_to "Login", new_user_session_path %></button>
            </div>
          <% end %>
        </span> <!-- End nav-bar-right -->
      </div> <!-- End col-md-10 -->
      </nav> <!-- End nav bar fixed top -->
      <div class="col-md-1"></div>
    </div> <!-- End row -->




  <!-- Main Content starts here -->

    <%= yield %>

  <!-- Footer starts here -->
  <div class="row sub-footer">
    <div class="col-md-1"></div>
      <div class="col-md-10">
        <p><strong>Created by <%= link_to "Katryn McIntosh", "http://www.linkedin.com/in/katrynmcintosh" %></strong><br>
        Project 1 // GA &ndash; Web Development Immersive</p>
      </div>
    <div class="col-md-1"></div>
  </div>
</div>

</body>
</html>

app/views/preferences/_preference.html.erb
<% @preferences.each do |preference| %>
<div class="preference">
  <h4><%= preference.score %> <span class="glyphicon glyphicon-star"></span>
   <span class="label label-purple pull-right"><%= preference.category.name %></span></h4>
  <div class="pull-right">
    <% if preference.preference_image.exists? %>
      <div class="index-image"><%= link_to image_tag(preference.preference_image.url(:thumb)), user_preference_path(current_user, preference) %></div><br>
    <% end %>
  </div>
  <h4><%= preference.item.name %></h4>
  <p><strong>Brand</strong><br>

  </p>

  <div class="edit">
    <strong><%= link_to "VIEW", user_preference_path(current_user, preference) %></strong>
  </div>

  <div class="edit">
    <%= link_to user_preference_path(current_user, preference), method: :delete, data: { confirm: 'Delete this preference?' } do %>
      <span class="glyphicon glyphicon-remove"></span>
    <% end %>
  </div>
</div>
<% end %>

app/views/preferences/edit.html.erb
<div class="home-spacer2"></div>

<!-- Error Messages -->
<% if @preference.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@preference.errors.count, "error") %> prohibited this
      preference from being saved:</h2>
    <ul>
      <% @preference.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- Form for creating a new preference -->
<div class="row">

  <div class="col-md-3 "></div>

  <div class="col-md-6 ">

    <h1 class="white-banner">Update your item</h1>
    <div class="home-spacer2"></div>

    <%= form_for @preference, :url => user_preference_path(current_user, @preference.id), :html => { :multipart => true } do |form| %>

    <%= form.label :category %><br>
    <%= form.select(:category, Category.all.map{ |c| [c.name, c.id] }) %><br>
    <br>
    <%= form.label :brand %><br>
    <%= form.select(:brand, Brand.all.map{ |b| [b.name, b.id] }) %>
    <br>
    <br>
    <%= form.label :item %><br>
    <%= form.select(:item, Item.all.map{ |i| [i.name, i.id] }) %>
    <br>
    <br>
    <!-- Upload image for a preference -->
    <%= form.file_field :preference_image %>
    <br>
    <%= form.label :comment  %><br>
    <%= form.text_field :comment  %>
    <br>

    <br>
     <%= label_tag :score %><br>

    <%= form.label :score, "1", :value => "1"  %>
    <%= form.radio_button :score, 1 %>
    <%= form.label :score, "2", :value => "2"  %>
    <%= form.radio_button :score, 2 %>
    <%= form.label :score, "3", :value => "3"  %>
    <%= form.radio_button :score, 3 %>
    <%= form.label :score, "4", :value => "4"  %>
    <%= form.radio_button :score, 4 %>
    <%= form.label :score, "5", :value => "5"  %>
    <%= form.radio_button :score, 5 %>
    <br>
    <br>
    <!-- Submit the form for a new preference -->
    <%= submit_tag("Submit") %>
    <% end %>
  </div>

  <div class="col-md-3 "></div>

</div>

<div class="home-spacer"></div>

app/views/preferences/index.html.erb
<div class="row">

  <div class="col-md-12">
    <h1 class="white-banner">All of my favorite things</h1>
    <%= render 'preferences/preference' %>
  </div>

</div>

app/views/preferences/new.html.erb
<div class="row">
  <div class="home-image"><%= image_tag("reco-home2.png") %></div>
</div>
<div class="row home-spacer">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <p class="tag-line">Rate your item</p>
  </div>
  <div class="col-md-4"></div>
</div>

<div class="row">

  <div class="col-md-4"></div>

  <div class="col-md-3">
    <div class="home-spacer2"></div>
    <% if @preference.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <h4><strong><%= pluralize(@preference.errors.count, "error") %> prohibited this item from being saved:</strong></h4>
        <ul><% @preference.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
    <% end %>
    <%= form_for @preference, :url => user_preferences_path, :html => { :multipart => true } do |form| %>
<%= form.label :category %><br>
      <%= form.select(:category, Category.all.map{ |c| [c.name, c.id] }) %><br>
      <br>
      <%= form.label :brand %><br>
      <%= form.select(:brand, Brand.all.map{ |b| [b.name, b.id] }) %><br><br>
      <%= form.label :item %><br>
      <%= form.select(:item, Item.all.map{ |i| [i.name, i.id] }) %><br>
      <br>

      <%= form.file_field :preference_image %><br>

      <%= form.label :comment  %><br>
      <%= form.text_field :comment  %><br>
      <br>

    <br>
    <%= label_tag :score %><br>

    <%= form.label :score, "1", :value => "1"  %>
    <%= form.radio_button :score, 1 %>
    <%= form.label :score, "2", :value => "2"  %>
    <%= form.radio_button :score, 2 %>
    <%= form.label :score, "3", :value => "3"  %>
    <%= form.radio_button :score, 3 %>
    <%= form.label :score, "4", :value => "4"  %>
    <%= form.radio_button :score, 4 %>
    <%= form.label :score, "5", :value => "5"  %>
    <%= form.radio_button :score, 5 %>

<br>
      <br>
  <!-- Submit the form for a new preference -->
      <%= submit_tag("Submit") %>
  <% end %>
    </div>
  <div class="col-md-3 "></div>
</div>
<div class="home-spacer2"></div>

app/views/preferences/show.html.erb
<div class="row">
  <div class="home-image"><%= image_tag("reco-home2.png") %></div>
</div>
<div class="row">
      <div class="col-md-1"></div>
        <div class="col-md-10">
          <%= render 'layouts/alerts' %>
        </div>
      <div class="col-md-1"></div>
    </div>
<div class="row">

  <div class="col-md-2 "></div>
  <div class="col-md-3 ">
    <% if @preference.preference_image.exists? %>
      <div class="index-image"><%= image_tag @preference.preference_image.url(:medium) %></div><br>
      <%= link_to edit_user_preference_path(current_user, @preference) do %>
        <button type="button" class="btn btn-default btn-med">
          <span class="glyphicon glyphicon-pencil"></span> Update image
        </button>
      <% end %>
    <% end %></div>

  <div class="col-md-5 ">

    <h2 class="update"><i><%= @preference.item.name %></i></h2>

      <%= link_to edit_user_preference_path(current_user, @preference) do %>
        <span class="glyphicon glyphicon-pencil pull-right"></span>
      <% end %><br>

    <h4 class="update"><strong>Brand </strong></h4>
    <%= link_to edit_user_preference_path(current_user, @preference) do %>
        <span class="glyphicon glyphicon-pencil pull-right"></span>
      <% end %>
      <hr />
    <h4><%= @preference.score %> <span class="glyphicon glyphicon-star"></span></h4>
    <p><strong>Comments</strong> <br>
    <%= @preference.comment %></p>
    <p><span class="label label-default"><%= @preference.category.name %></span></p>

    <div class="edit">
      <%= link_to edit_user_preference_path(current_user, @preference) do %>
      <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
    </div>


    <div class="edit">
      <%= link_to user_preference_path(current_user, @preference), method: :delete, data: { confirm: 'Delete this preference?' } do %>
        <span class="glyphicon glyphicon-remove"></span>
      <% end %><br>
    </div>
  </div>

  <div class="col-md-2 "></div>

</div>
<div class="row">
<div class="home-spacer2"></div>
<div class="home-spacer2"></div>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>